"""init

Revision ID: 0172be912d9b
Revises: 51be785ad719
Create Date: 2022-02-21 14:54:06.503087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0172be912d9b'
down_revision = '51be785ad719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sizes', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.create_unique_constraint(None, 'Sizes', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Sizes', type_='unique')
    op.drop_column('Sizes', 'name')
    # ### end Alembic commands ###
