"""init

Revision ID: 0c6334b404a6
Revises: 
Create Date: 2022-02-03 17:24:48.246099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6334b404a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('login', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password', sa.VARBINARY(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_registered', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('Delivery_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('Statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Streets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('login', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARBINARY(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('Customer_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('streets_id', sa.Integer(), nullable=False),
    sa.Column('house_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=False),
    sa.Column('other_info', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['Cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['Regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['streets_id'], ['Streets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Material_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['Categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('delivery_type_id', sa.Integer(), nullable=False),
    sa.Column('is_payed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_type_id'], ['Delivery_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['Statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('article', sa.VARCHAR(length=255), nullable=False),
    sa.Column('good_1c_id', sa.Integer(), nullable=True),
    sa.Column('material_list_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_list_id'], ['Material_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['Structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('good_1c_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Variations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('variation_1c_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.Integer(), nullable=False),
    sa.Column('is_sale', sa.BOOLEAN(), nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['Colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['good_id'], ['Goods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size'], ['Sizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('variation_1c_id')
    )
    op.create_table('Images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('png_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('model_info', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['variation_id'], ['Variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('png_url'),
    sa.UniqueConstraint('url')
    )
    op.create_table('Variation_in_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variation_id'], ['Variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Variation_in_order')
    op.drop_table('Images')
    op.drop_table('Variations')
    op.drop_table('Goods')
    op.drop_table('Orders')
    op.drop_table('Material_lists')
    op.drop_table('Customer_addresses')
    op.drop_table('Users')
    op.drop_table('Structure')
    op.drop_table('Streets')
    op.drop_table('Statuses')
    op.drop_table('Sizes')
    op.drop_table('Regions')
    op.drop_table('Materials')
    op.drop_table('Delivery_types')
    op.drop_table('Customers')
    op.drop_table('Colors')
    op.drop_table('Cities')
    op.drop_table('Categories')
    # ### end Alembic commands ###
