"""init

Revision ID: 13cf9c51f27c
Revises: 0172be912d9b
Create Date: 2022-02-21 15:14:15.285861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cf9c51f27c'
down_revision = '0172be912d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
