"""patch

Revision ID: 1be0360b9585
Revises: b486f259ac6b
Create Date: 2022-02-18 15:01:04.164535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be0360b9585'
down_revision = 'b486f259ac6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Material_lists_material_id_fkey', 'Material_lists', type_='foreignkey')
    op.create_foreign_key(None, 'Material_lists', 'Materials', ['material_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Material_lists', type_='foreignkey')
    op.create_foreign_key('Material_lists_material_id_fkey', 'Material_lists', 'Categories', ['material_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
