"""init

Revision ID: 41c77c74df9d
Revises: 5b3fd0704c9d
Create Date: 2022-02-21 15:15:12.178358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c77c74df9d'
down_revision = '5b3fd0704c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Colors', sa.Column('code', sa.VARCHAR(length=50), nullable=False))
    op.create_unique_constraint(None, 'Colors', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Colors', type_='unique')
    op.drop_column('Colors', 'code')
    # ### end Alembic commands ###
