"""init

Revision ID: 51be785ad719
Revises: b6bb7cf93dd1
Create Date: 2022-02-21 14:53:56.090118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51be785ad719'
down_revision = 'b6bb7cf93dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Sizes_value_key', 'Sizes', type_='unique')
    op.drop_column('Sizes', 'value')
    op.create_unique_constraint(None, 'Structures', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Structures', type_='unique')
    op.add_column('Sizes', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('Sizes_value_key', 'Sizes', ['value'])
    # ### end Alembic commands ###
