"""patch

Revision ID: 5b1cfe3fdc52
Revises: 1be0360b9585
Create Date: 2022-02-20 14:13:58.503861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1cfe3fdc52'
down_revision = '1be0360b9585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Structures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'Goods', 'Structures', ['structure_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Goods', type_='foreignkey')
    op.drop_table('Structures')
    # ### end Alembic commands ###
