"""init

Revision ID: 5b3fd0704c9d
Revises: 13cf9c51f27c
Create Date: 2022-02-21 15:14:58.375540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3fd0704c9d'
down_revision = '13cf9c51f27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Colors_code_key', 'Colors', type_='unique')
    op.drop_column('Colors', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Colors', sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('Colors_code_key', 'Colors', ['code'])
    # ### end Alembic commands ###
