"""init

Revision ID: b6bb7cf93dd1
Revises: 
Create Date: 2022-02-21 12:40:37.773593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bb7cf93dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Structures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('Goods_material_list_id_fkey', 'Goods', type_='foreignkey')
    op.create_foreign_key(None, 'Goods', 'Structures', ['structure_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Goods', 'material_list_id')
    op.add_column('Material_lists', sa.Column('good_id', sa.Integer(), nullable=False))
    op.drop_constraint('Material_lists_material_id_fkey', 'Material_lists', type_='foreignkey')
    op.create_foreign_key(None, 'Material_lists', 'Materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Material_lists', 'Goods', ['good_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Material_lists', type_='foreignkey')
    op.drop_constraint(None, 'Material_lists', type_='foreignkey')
    op.create_foreign_key('Material_lists_material_id_fkey', 'Material_lists', 'Categories', ['material_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Material_lists', 'good_id')
    op.add_column('Goods', sa.Column('material_list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Goods', type_='foreignkey')
    op.create_foreign_key('Goods_material_list_id_fkey', 'Goods', 'Material_lists', ['material_list_id'], ['id'], ondelete='CASCADE')
    op.drop_table('Structures')
    # ### end Alembic commands ###
