"""patch

Revision ID: f8a4511d0fc7
Revises: 3c5b9da898f1
Create Date: 2022-02-28 12:19:35.354109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a4511d0fc7'
down_revision = '3c5b9da898f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Goods_default_variation_fkey', 'Goods', type_='foreignkey')
    op.create_foreign_key(None, 'Goods', 'Variations', ['default_variation'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Goods', type_='foreignkey')
    op.create_foreign_key('Goods_default_variation_fkey', 'Goods', 'Variations', ['default_variation'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
